name: CI for Android and iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-test:
    name: Android Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Android unit tests
        run: ./gradlew testDebugUnitTest

  ios-test:
    name: iOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install dependencies (if Podfile exists)
        run: |
          cd iosApp
          if [ -f "Podfile" ]; then
            pod install
          else
            echo "No Podfile found, skipping pod install."
          fi

      - name: Find available scheme
        run: |
          cd iosApp
          AVAILABLE_SCHEMES=$(xcodebuild -list | awk '/Schemes:/ {found=1; next} found && NF' | head -n 1)
          if [ -z "$AVAILABLE_SCHEMES" ]; then
            echo "No available schemes found. Make sure the scheme is shared."
            exit 1
          fi
          echo "Available Scheme: $AVAILABLE_SCHEMES"
          echo "SCHEME_NAME=$AVAILABLE_SCHEMES" >> $GITHUB_ENV

      - name: Run iOS tests
        run: |
          cd iosApp
          if [ -d "iosApp.xcworkspace" ]; then
            xcodebuild test \
              -workspace iosApp.xcworkspace \
              -scheme "$SCHEME_NAME" \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
          elif [ -d "iosApp.xcodeproj" ]; then
            xcodebuild test \
              -project iosApp.xcodeproj \
              -scheme "$SCHEME_NAME" \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
          else
            echo "No Xcode project or workspace found, skipping iOS tests."
            exit 1
          fi
