name: CI for Kotlin Multiplatform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-test:
    name: Android Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Android unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run all KMP tests
        run: ./gradlew allTests --warning-mode all

  ios-test:
    name: iOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: List available Gradle tasks (for debugging)
        run: ./gradlew tasks

      - name: Run iOS Kotlin Multiplatform tests
        run: |
          ./gradlew iosX64Test iosSimulatorArm64Test --warning-mode all

  firebase-ios-test:
    name: Firebase Test Lab (iOS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: iconic-scholar-452807-h3

      - name: Save Service Account Key to JSON
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcloud-key.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud config set project iconic-scholar-452807-h3
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json

      - name: Upload iOS app to Firebase Test Lab
        run: |
          gcloud firebase test ios run \
            --test app.ipa \
            --device model=iphone14,version=16.0,locale=en,orientation=portrait